/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:\Users\kethl\Desktop\burger-stack-ts\src\assets\models\sticker_roller_3.glb -o c:\Users\kethl\Desktop\burger-stack-ts\src\components\models\StickerRoller.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import modelUrl from '../../assets/models/sticker_roller_3.glb?url'
import { useEffect, useCallback } from 'react'
import { gsap } from 'gsap'
import { useGSAP } from '@gsap/react'
type ActionName = 'Sticker Roll' | 'Sticker Peel'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Roller_2: THREE.Mesh
    polySurface1: THREE.Mesh
    pCylinder1: THREE.Mesh
    polySurface1001: THREE.Mesh
    screw002: THREE.Mesh
    Beta_sticker_logo_back001: THREE.Mesh
    Beta_sticker_logo_front001: THREE.Mesh
  }
  materials: {
    Roller: THREE.MeshStandardMaterial
    Screw: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    ['logo 1 sticker white']: THREE.MeshStandardMaterial
    ['logo sticker new']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type StickerRollerProps = React.JSX.IntrinsicElements['group'] & {
  sticker: string
  onPeelComplete?: () => void
}
function StickerRoller({ sticker, onPeelComplete, ...props }: StickerRollerProps) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF(modelUrl) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  const texture = useTexture(sticker, (txt) => { txt.flipY = false })

  const handleStickerClick = useCallback(() => {
    const mixer = actions['Sticker Peel']?.getMixer()
    const clip = animations.find(a => a.name === 'Sticker Peel')
    if (!mixer || !clip) return

    actions['Sticker Roll']?.stop()

    const peelAction = mixer.clipAction(clip)
    peelAction.reset()
    peelAction.setLoop(THREE.LoopOnce, 1)
    peelAction.clampWhenFinished = true
    peelAction.play()

    const onFinished = (e: { action: THREE.AnimationAction }) => {
      if (e.action !== peelAction) return
      mixer.removeEventListener('finished', onFinished)
      onPeelComplete?.()
    }
    mixer.addEventListener('finished', onFinished)
  }, [actions, animations, onPeelComplete])

  useGSAP(() => {
    if (!group.current) return
    gsap.from(group.current.rotation, {
      y: Math.PI / 2,
      duration: 1.5,
      ease: "power3.out",
    })
    gsap.from(group.current.position, {
      x: -25,
      duration: 1,
      ease: "power3.out",
    })
  }, { scope: group })

  useEffect(() => {
    const mixer = actions['Sticker Roll']?.getMixer()
    const clip = animations.find(a => a.name === 'Sticker Roll')
    if (!mixer || !clip) return

    const action = mixer.clipAction(clip)
    action.play()
    action.paused = true
    action.time = 0

    const timeout = setTimeout(() => {
      action.paused = false
      action.setLoop(THREE.LoopOnce, 1)
      action.clampWhenFinished = true
    }, 1000)

    return () => clearTimeout(timeout)
  }, [actions, animations, texture, group, onPeelComplete])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="roll" position={[-6.151, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.644} />
        <mesh name="Roller_2" geometry={nodes.Roller_2.geometry} material={materials.Roller} position={[9.715, 0.005, 0.972]} rotation={[Math.PI / 2, 0, 0]} scale={0.782}>
          <mesh name="polySurface1" geometry={nodes.polySurface1.geometry} material={materials.Screw} position={[0, 0, 2.465]} rotation={[Math.PI, 0, 0]} scale={0.176}>
            <mesh name="pCylinder1" geometry={nodes.pCylinder1.geometry} material={materials.lambert1} />
          </mesh>
          <mesh name="polySurface1001" geometry={nodes.polySurface1001.geometry} material={materials.Screw} position={[0, 0, -1.706]} scale={0.176} />
          <mesh name="screw002" geometry={nodes.screw002.geometry} material={materials.Screw} position={[0.002, 0.005, -2.859]} rotation={[-Math.PI / 2, -0.523, 0]} scale={0.593} />
        </mesh>
        <mesh name="Beta_sticker_logo_back001" geometry={nodes.Beta_sticker_logo_back001.geometry} material={materials['logo 1 sticker white']} morphTargetDictionary={nodes.Beta_sticker_logo_back001.morphTargetDictionary} morphTargetInfluences={nodes.Beta_sticker_logo_back001.morphTargetInfluences} position={[0, 0, 0.031]} onClick={handleStickerClick} />
        <mesh name="Beta_sticker_logo_front001" geometry={nodes.Beta_sticker_logo_front001.geometry} material={materials['logo sticker new']} morphTargetDictionary={nodes.Beta_sticker_logo_front001.morphTargetDictionary} morphTargetInfluences={nodes.Beta_sticker_logo_front001.morphTargetInfluences} position={[0, 0, -0.001]} onClick={handleStickerClick} >
          <meshStandardMaterial map={texture} transparent />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload(modelUrl)
export default StickerRoller  
